---
title: "Project - Part 3"
author: "Ryan Thackston"
date: "5/2/2021"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(knitr)
library(kableExtra)
options(knitr.table.format = "latex")
```

## Table S1:

```{r S1}
#install.packages("kableExtra")
# For dev version
# install.packages("devtools")
#devtools::install_github("haozhu233/kableExtra")
library(kableExtra)
setwd("D:/COSC_6323_Statistics_for_Researchers/Project")
S1_data <- read.csv("S1_df_final.csv", header=T, row.names=1)
S1_data[is.na(S1_data)] <- " "

  kbl(S1_data,caption = "Table:S1",
      col.names =c("(1) \n $X_{SA}$","(2) \n $X_{CIP}$","(3) \n $X_{SA\\&CIP}$","(4) \n $X_{SA}$","(5) \n $X_{CIP}$","(6) \n $X_{SA \\& CIP}$"),format = "latex", escape = F,booktabs=T)  %>% pack_rows(" ", 1, 7, hline_before = T) %>%
  pack_rows(" ", 8, 14,hline_before = T) %>%
  pack_rows(" ", 15, 16,hline_before = T)%>% 
  column_spec(c(2:7), width = "6em") %>%
  kable_classic(full_width = F, html_font = "Cambria")
  
```

```{r S2}


S2_data <- read.csv("S2_df_final.csv", header=T, row.names=1)
S2_data[is.na(S2_data)] <- " "
  kbl(S2_data,caption = "Table:S2",
      col.names =c("(1) \n $\\tiny X_{Distant,SA}$","(2) \n $\\tiny X_{Distant,CIP}$","(3) \n $\\tiny X_{Neibor,SA\\&CIP}$","(4) \n $\\tiny X_{Distant,SA}$","(5) \n $\\tiny X_{Distant,CIP}$","(6) \n $\\tiny X_{Distant,SA \\& CIP}$"),format = "latex", escape = F,booktabs=T)  %>% pack_rows(" ", 1, 7, hline_before = T) %>%
  pack_rows(" ", 8, 14,hline_before = T) %>%
  pack_rows(" ", 15, 16,hline_before = T)%>% 
  column_spec(c(0:7), width = "6em") %>%
  kable_classic(full_width = F, html_font = "Cambria")
  
```

```{r s3}
S3_data <- read.csv("S3_df_final.csv", header=T, row.names=1)
S3_data[is.na(S3_data)] <- " "
  kbl(S3_data,caption = "Table:S3",
      col.names =c("(1) \n $\\tiny X_{Distant,SA}$","(2) \n $\\tiny X_{Distant,CIP}$","(3) \n $\\tiny X_{Distant,SA\\&CIP}$","(4) \n $\\tiny X_{Distant,SA}$","(5) \n $\\tiny X_{Distant,CIP}$","(6) \n $\\tiny X_{Distant,SA \\& CIP}$"),format = "latex", escape = F,booktabs=T)  %>% pack_rows(" ", 1, 7, hline_before = T) %>%
  pack_rows(" ", 8, 14,hline_before = T) %>%
  pack_rows(" ", 15, 16,hline_before = T)%>% 
  column_spec(c(0:7), width = "6em") %>%
  kable_classic(full_width = F, html_font = "Cambria")
```

```{r s4}
S4_data <- read.csv("S4_df_final.csv", header=T, row.names=1)
S4_data[is.na(S4_data)] <- " "

  kbl(S4_data,caption = "Table:S4",
      col.names =c("(1) \n $ z_{p}$","(2) \n $ z_{p}$","(3) \n $ z_{p}$","(4) \n $ z_{p}$","(5) \n $ z_{p}$","(6) \n $ z_{p}$"),format = "latex", escape = F,booktabs=T)  %>% pack_rows(" ", 1, 3, hline_before = T) %>%
  pack_rows(" ", 4, 5,hline_before = T) %>%
    pack_rows(" ", 6, 7,hline_before = T) %>%
    pack_rows(" ", 8, 9,hline_before = T) %>%
  pack_rows(" ", 10, 12,hline_before = T)%>% 
    pack_rows(" ", 13, 17,hline_before = T)%>% 
    pack_rows(" ", 18, 19,hline_before = T)%>% 
  column_spec(c(1:7), width = "6em") %>%
  kable_classic(full_width = F, html_font = "Cambria")
```

```{r s5}
S5_data <- read.csv("S5_df_final.csv", header=T, row.names=1)
S5_data[is.na(S5_data)] <- " "

  kbl(S5_data,caption = "Table:S5",
      col.names =c("(1) \n $ z_{p}$","(2) \n $ z_{p}$","(3) \n $ z_{p}$"),format = "latex", escape = F,booktabs=T)  %>% pack_rows(" ", 1, 4, hline_before = T) %>%
  pack_rows(" ", 5, 6,hline_before = T) %>%
    pack_rows(" ", 7, 8,hline_before = T) %>%
    pack_rows(" ", 9, 10,hline_before = T) %>%
  pack_rows(" ", 11, 15,hline_before = T)%>% 
    pack_rows(" ", 16, 19,hline_before = T)%>% 
    #column_spec(c(0:2), width = "5em") %>%
  column_spec(0, width = "10em") %>%
  kable_classic(full_width = F, html_font = "Cambria")
```

```{r fig5A}
library(car)
library(stats)
library(ggplot2)
library(readr)
library(tidyverse)
A_data <- data.frame(S1_data[1,1],S1_data[1,2],S1_data[1,3],
                      S2_data[1,1],S2_data[1,2],S2_data[1,3],
                      S3_data[1,1], S3_data[1,2],S3_data[1,3])
A_data_split <- str_split_fixed(A_data, " ",3)
A_data_coef <- as.numeric(A_data_split[,1])
A_data_SE <- parse_number(A_data_split[,3])

values <- data.frame(Beta=100*(A_data_coef-1),
               se=100*c(A_data_SE),
               Type=c("Broad","Broad","Broad","Neighboring","Neighboring","Neighboring","Distant","Distant","Distant"),
               Domain=c("SA","CIP","SA and CIP","SA","CIP","SA and CIP","SA","CIP","SA and CIP"))

values$Type<-factor(values$Type,levels=c("Broad","Neighboring","Distant"))
values$Domain<-factor(values$Domain,levels = c("SA","CIP","SA and CIP"))

pd = position_dodge(2)

plot1 <- ggplot(values, aes(
    x = Type,
    y = Beta,
    color = factor(Domain)
)) +
    geom_errorbar(
        aes(ymin = Beta-se,
            ymax = Beta+se),
        width = .2,
        size = .7,
        position = position_dodge(.5)
    ) +
    geom_point(shape = 15,
               size = 3,
               position = position_dodge(.5)) +
    theme_bw() +
    theme(
        legend.position = "top",
        legend.direction = "horizontal",
        legend.box = "horizontal",
        panel.grid = element_blank(),
        axis.title.y = element_text(vjust = 1.8),
        axis.title.x = element_text(vjust = -0.5),
        axis.title = element_text(face = "bold")
    ) +
    scale_color_manual(label=c("SA","CIP","SA and CIP"),values = c("light grey", "dark grey", "black")) +
    geom_hline(yintercept=0, linetype="dashed", color = "black") +
    ylab("Percent increase in Odds")

plot1
```

```{r figure5b}

C_data <- data.frame(S1_data[8,4],S1_data[8,5],S1_data[8,6],
                      S2_data[8,4],S2_data[8,5],S2_data[8,6],
                      S3_data[8,4], S3_data[8,5],S3_data[8,6])
C_data_split <- str_split_fixed(C_data, " ",3)
C_data_coef <- as.numeric(C_data_split[,1])
C_data_SE <- parse_number(C_data_split[,3])

values <- data.frame(Beta=100*(C_data_coef-1),
               se=100*c(C_data_SE),
               Type=c("Broad","Broad","Broad","Neighboring","Neighboring","Neighboring","Distant","Distant","Distant"),
               Domain=c("SA","CIP","SA and CIP","SA","CIP","SA and CIP","SA","CIP","SA and CIP"))

values$Type<-factor(values$Type,levels=c("Broad","Neighboring","Distant"))
values$Domain<-factor(values$Domain,levels = c("SA","CIP","SA and CIP"))

pd = position_dodge(2)

plot2 <- ggplot(values, aes(
    x = Type,
    y = Beta,
    color = factor(Domain)
)) +
    geom_errorbar(
        aes(ymin = Beta-se,
            ymax = Beta+se),
        width = .2,
        size = .7,
        position = position_dodge(.5)
    ) +
    geom_point(shape = 15,
               size = 3,
               position = position_dodge(.5)) +
    theme_bw() +
    theme(
        legend.position = "top",
        legend.direction = "horizontal",
        legend.box = "horizontal",
        panel.grid = element_blank(),
        axis.title.y = element_text(vjust = 1.8),
        axis.title.x = element_text(vjust = -0.5),
        axis.title = element_text(face = "bold")
    ) +
    scale_color_manual(label=c("SA","CIP","SA and CIP"),values = c("light grey", "dark grey", "black")) +
    geom_hline(yintercept=0, linetype="dashed", color = "black") +
    ylab("Percent increase in Odds")
plot2
```





```{r figure5c}

C_data <- data.frame(S4_data[4,1],S4_data[5,1],S4_data[10,4],
                      S4_data[6,2],S4_data[7,2],S4_data[11,5],
                      S4_data[8,3], S4_data[9,3],S4_data[12,6])
C_data_split <- str_split_fixed(C_data, " ",3)
C_data_coef <- parse_number(C_data_split[,1])
C_data_SE <- parse_number(C_data_split[,2])

values <- data.frame(Beta=100*(C_data_coef*1.24),
               se=100*c(C_data_SE*1.24),
               Type=c("Broad","Broad","Broad","Neighboring","Neighboring","Neighboring","Distant","Distant","Distant"),
               Domain=c("SA","CIP","SA and CIP","SA","CIP","SA and CIP","SA","CIP","SA and CIP"))

values$Type<-factor(values$Type,levels=c("Broad","Neighboring","Distant"))
values$Domain<-factor(values$Domain,levels = c("SA","CIP","SA and CIP"))

pd = position_dodge(2)

plot3<- ggplot(values, aes(
    x = Type,
    y = Beta,
    color = factor(Domain)
)) +
    geom_errorbar(
        aes(ymin = Beta-se,
            ymax = Beta+se),
        width = .2,
        size = .7,
        position = position_dodge(.5)
    ) +
    geom_point(shape = 15,
               size = 3,
               position = position_dodge(.5)) +
    theme_bw() +
    theme(
        legend.position = "top",
        legend.direction = "horizontal",
        legend.box = "horizontal",
        panel.grid = element_blank(),
        axis.title.y = element_text(vjust = 1.8),
        axis.title.x = element_text(vjust = -0.5),
        axis.title = element_text(face = "bold")
    ) +
    scale_color_manual(label=c("SA","CIP","SA and CIP"),values = c("light grey", "dark grey", "black")) +
    geom_hline(yintercept=0, linetype="dashed", color = "black") +
    ylab("Percent increase in citations associated with X")
plot3
```

```{r fig5d}
C_data <- data.frame(S5_data[5,1],S5_data[6,1],S5_data[6,1],
                      S5_data[7,2],S5_data[8,2],S5_data[8,2],
                      S5_data[9,3], S5_data[10,3],S5_data[10,3])
C_data_split <- str_split_fixed(C_data, " ",3)
C_data_coef <- parse_number(C_data_split[,1])
C_data_coef[3] <-C_data_coef[1]+C_data_coef[3]
C_data_coef[6] <-C_data_coef[4]+C_data_coef[6]
C_data_coef[9] <-C_data_coef[7]+C_data_coef[9]
C_data_SE <- parse_number(C_data_split[,2])
C_data_SE[3] <-C_data_SE[1]+C_data_SE[3]
C_data_SE[6] <-C_data_SE[4]+C_data_SE[6]
C_data_SE[9] <-C_data_SE[7]+C_data_SE[9]
values <- data.frame(Beta=100*(C_data_coef*1.24),
               se=100*c(C_data_SE*1.24),
               Type=c("Broad","Broad","Broad","Neighboring","Neighboring","Neighboring","Distant","Distant","Distant"),
               Domain=c("sigma_gamma_X","sigma_delta_X+","sigma(gammaX+deltaX+)","sigma_gamma_X","sigma_delta_X+","sigma(gammaX+deltaX+)","sigma_gamma_X","sigma_delta_X+","sigma(gammaX+deltaX+)"))

values$Type<-factor(values$Type,levels=c("Broad","Neighboring","Distant"))
values$Domain<-factor(values$Domain,levels = c("sigma_gamma_X","sigma_delta_X+","sigma(gammaX+deltaX+)"))

pd = position_dodge(2)

plot4<- ggplot(values, aes(
    x = Type,
    y = Beta,
    color = factor(Domain)
)) +
    geom_errorbar(
        aes(ymin = Beta-se,
            ymax = Beta+se),
        width = .2,
        size = .7,
        position = position_dodge(.5)
    ) +
    geom_point(shape = 15,
               size = 3,
               position = position_dodge(.5)) +
    theme_bw() +
    theme(
        legend.position = "top",
        legend.direction = "horizontal",
        legend.box = "horizontal",
        panel.grid = element_blank(),
        axis.title.y = element_text(vjust = 1.8),
        axis.title.x = element_text(vjust = -0.5),
        axis.title = element_text(face = "bold")
    ) +
    scale_color_manual(label=c("sigma_gamma_X","sigma_delta_X+","sigma(gammaX+deltaX+)"),values = c("light green", "red", "dark green")) +
    geom_hline(yintercept=0, linetype="dashed", color = "black") +
    ylab("Percent increase in citations associated with X")
plot4
```

